options:
  logging: CLOUD_LOGGING_ONLY
  logsBucket: gs://ultradeeptech-cloudbuild-logs

steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ultradeeptech/grcshield', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ultradeeptech/grcshield']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'grcshield', '--image', 'gcr.io/ultradeeptech/grcshield', '--platform', 'managed', '--region', 'us-central1']
images:
- 'gcr.io/ultradeeptech/grcshield'

